{{- with .Values.homeassistant.ingress }}
{{- if .enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homeassistant-ingress
  labels:
    {{- include "homeassistant.labels" $ | nindent 4 }}
  {{- if .annotations }}
  annotations:
    {{- .annotations | toYaml | nindent 4 }}
  {{- end }}
spec:
  {{- if .className }}
  ingressClassName: {{ .className }}
  {{- end }}
  rules:
    - host: {{ required "Host required for homeassistant.ingress" .host }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: homeassistant
                port:
                  name: http-ha-svc
  {{- if .tls }}
  tls:
    {{- .tls | toYaml | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
