apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  labels:
    {{- include "homeassistant.labels" $ | nindent 4 }}
spec:
  selector:
    {{- include "homeassistant.selectorLabels" $ | nindent 4 }}
  ports:
    - name: http-ha-svc
      port: 80
      targetPort: http-ha-pod
