### General ###
tz: ""
nameOverride: ""

### Home Assistant ###
homeassistant:

  fullnameOverride: ""

  image:
    repository: homeassistant/home-assistant
    tag: ""  # default: .Chart.AppVersion

  ingress:
    enabled: false
    className: ""
    annotations: {}
    host: ""
    tls: []

  persistence:
    storageClass: ""
    size: 8Gi
    accessMode: ReadWriteOnce

  hostNetwork: false

  dnsPolicy: Default

  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  securityContext: {}
    # allowPrivilegeEscalation: false
    # readOnlyRootFilesystem: true
    # seccompProfile:
    #   type: RuntimeDefault

  resources: {}
    # limits:
    #   cpu: 2000m
    #   memory: 2Gi
    # requests:
    #   cpu: 250m
    #   memory: 1Gi

  livenessProbe:
    httpGet:
      path: /
      port: http-ha-pod

  readinessProbe:
    httpGet:
      path: /
      port: http-ha-pod

  mqtt:
    username: homeassistant
    # password: homeassistant-secr3t // not needed - set in UI
    mosquitto_hash: $7$101$NZlsYzqgcx0X3COA$1l6Uk552Kvv0vSUyJMB1Wl4J1xiiE6R42PZ73Cpw/DDQQxCc5jWdfp72u6epaOvIf+/bKGSvrQD71/lKbdMiYw==


### Mosquitto ###
mosquitto:

  fullnameOverride: ""

  image:
    repository: eclipse-mosquitto
    tag: "2.0.21"

  persistence:
    storageClass: ""
    accessMode: ReadWriteOnce
    size: 256Mi

  nodeSelector: {}
  podAnnotations: {}
  podLabels: {}
  podSecurityContext:
    runAsUser: 1883
    runAsGroup: 1883
    fsGroup: 1883
  securityContext: {}

  serviceAccount:
    create: true
    automount: true
    annotations: {}
    name: ""


### ZigBee2MQTT ###
zigbee2mqtt:

  enabled: false

  fullnameOverride: ""

  image:
    repository: koenkk/zigbee2mqtt
    tag: "2.4.0"


  ingress:
    enabled: false
    className: ""
    annotations: {}
    host: ""
    tls: []

  persistence:
    storageClass: ""
    accessMode: ReadWriteOnce
    size: 1Gi

  mqtt:
    username: zigbee2mqtt
    password: z2m-secr3t
    mosquitto_hash: $7$101$mQhgJLIxXVtFpOwU$QfIOPODCW2RhDCoLSxMsKqGKTcUmWUucg3dUp04DGFmjVAQ0Vg2TAAdNtfclQEaYNpbi5pfOD1xd9jYj7U8r9g==


  serial:
    path: ""

  resources: {}

  livenessProbe:
    httpGet:
      path: /
      port: http-z2m-pod

  readinessProbe:
    httpGet:
      path: /
      port: http-z2m-pod

  nodeSelector: {}
  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  securityContext:
    privileged: true

  serviceAccount:
    create: true
    automount: true
    annotations: {}
    name: ""

### Ring MQTT ###
ringMqtt:

  enabled: false

  fullnameOverride: ""

  image:
    repository: tsightler/ring-mqtt
    tag: "5.8.1"

  persistence:
    storageClass: ""
    accessMode: ReadWriteOnce
    size: 256Mi

  mqtt:
    username: ring-mqtt
    password: ring-secr3t
    mosquitto_hash: $7$101$hnS4aRwOkfjnonat$qce/XhBCL1PNL+pREyXDhyWYuZ7jCFMI0e8Kwl1zxyS+1tnvJAlJyVOO+5oeS+JHTdedvLnJfzrNA8DJrLoofg==


  nodeSelector: {}
  podAnnotations: {}
  podLabels: {}
  podSecurityContext:
    runAsUser: 1883
    runAsGroup: 1883
    fsGroup: 1883
  securityContext: {}

  serviceAccount:
    create: true
    automount: true
    annotations: {}
    name: ""


extraObjects: {}
