{{- with .Values.zigbee2mqtt }}
{{- if .enabled }}
{{- with .persistence }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zigbee2mqtt-data
  labels:
    {{- include "zigbee2mqtt.labels" $ | nindent 4 }}
spec:
  {{- if .storageClass }}
  storageClassName: {{ .storageClass }}
  {{- end }}
  accessModes:
    - {{ .accessMode }}
  resources:
    requests:
      storage: {{ .size }}
{{- end }}
{{- end }}
{{- end }}
