apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  labels:
    {{- include "mosquitto.labels" $ | nindent 4 }}
data:
  mosquitto.conf: |
    persistence true
    persistence_location /mosquitto/data

    per_listener_settings true

    log_type subscribe
    log_type unsubscribe
    log_type websockets
    log_type error
    log_type warning
    log_type notice
    log_type information
    log_dest stdout

    listener 1883
    protocol mqtt

    # listener 9001
    # protocol websockets

    allow_anonymous false
    password_file  /mosquitto/config/passwd
