apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  labels:
    {{- include "mosquitto.labels" $ | nindent 4 }}
spec:
  selector:
    {{- include "mosquitto.selectorLabels" $ | nindent 4 }}
  ports:
    - name: mqtt-svc
      port: 1883
    # - name: mqtt-ws-svc
    #   port: 9001
