{{- with .Values.mosquitto.serviceAccount }}
{{- if .create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mosquitto.serviceAccountName" $ }}
  labels:
    {{- include "mosquitto.labels" $ | nindent 4 }}
  annotations:
    {{- .annotations | toYaml | nindent 4 }}
automountServiceAccountToken: {{ .automount }}
{{- end }}
{{- end }}
